name: Scan Quotidien Pépites Rim

# 1. QUAND LANCER LE ROBOT ?
on:
  schedule:
    - cron: '0 8 * * *' # Tous les matins à 8h00 (UTC)
  workflow_dispatch:      # Permet de cliquer sur un bouton pour le lancer manuellement

# 2. QUE DOIT FAIRE LE ROBOT ?
jobs:
  scrape:
    runs-on: ubuntu-latest # On utilise Linux (pas d'erreurs Visual C++ ici !)
    
    steps:
      - name: Récupérer le code de Rim
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installer les outils (Playwright & Supabase)
        run: |
          pip install supabase playwright
          playwright install chromium

      - name: Lancer la recherche de pépites
        env:
          # On récupère tes clés secrètes depuis les "Settings" de GitHub
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python rim.py
